##### Portainer Docker Web GUI #####
  portainer:
    container_name: portainer
    image: 'portainer/portainer:latest'
    restart: always
    ports:
      - '9000:9000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
##### End Portainer Docker Web GUI #####